const PRODUCT_LIST = "PRODUCT_LIST";
const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
const ADD_TO_CART = "ADD_TO_CART";
const CLEAR_CART = "CLEAR_CART";

export { PRODUCT_LIST, SET_PRODUCT_LIST, ADD_TO_CART, CLEAR_CART };
