const PRODUCT_LIST = "PRODUCT_LIST";
const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
const ADD_TO_CART = "ADD_TO_CART";
const CLEAR_CART = "CLEAR_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const PRODUCT_SEARCH = "PRODUCT_SEARCH";

export {
  PRODUCT_LIST,
  SET_PRODUCT_LIST,
  ADD_TO_CART,
  CLEAR_CART,
  REMOVE_FROM_CART,
  PRODUCT_SEARCH,
};
